//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSL.AST.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSL.AST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается бинарное выражение.
        /// </summary>
        internal static string BinaryExpressionExpected {
            get {
                return ResourceManager.GetString("BinaryExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается закрывающая скобка - ].
        /// </summary>
        internal static string CloseBracketExpected {
            get {
                return ResourceManager.GetString("CloseBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается закрывающая скобка - ).
        /// </summary>
        internal static string CloseParentExpected {
            get {
                return ResourceManager.GetString("CloseParentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается запятая - ,.
        /// </summary>
        internal static string CommaExpected {
            get {
                return ResourceManager.GetString("CommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;Цикл&quot;.
        /// </summary>
        internal static string DoExpected {
            get {
                return ResourceManager.GetString("DoExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;КонецЦикла&quot;.
        /// </summary>
        internal static string EndDoExpected {
            get {
                return ResourceManager.GetString("EndDoExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;КонецФункции&quot;.
        /// </summary>
        internal static string EndFunctionTokenExpected {
            get {
                return ResourceManager.GetString("EndFunctionTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;КонецЕсли&quot;.
        /// </summary>
        internal static string EndIfExpected {
            get {
                return ResourceManager.GetString("EndIfExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается символ конца метки - :.
        /// </summary>
        internal static string EndMarkExpected {
            get {
                return ResourceManager.GetString("EndMarkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;КонецПроцедуры&quot;.
        /// </summary>
        internal static string EndProcedureTokenExpected {
            get {
                return ResourceManager.GetString("EndProcedureTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается &quot;#КонецОбласти&quot;.
        /// </summary>
        internal static string EndRegionExpected {
            get {
                return ResourceManager.GetString("EndRegionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;КонецПопытки&quot;.
        /// </summary>
        internal static string EndTryExpected {
            get {
                return ResourceManager.GetString("EndTryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается оператор присваивания - =.
        /// </summary>
        internal static string EqualExpected {
            get {
                return ResourceManager.GetString("EqualExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;Исключение&quot;.
        /// </summary>
        internal static string ExceptExpected {
            get {
                return ResourceManager.GetString("ExceptExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается выражение.
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается идентификатор.
        /// </summary>
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;Из&quot;.
        /// </summary>
        internal static string InExpected {
            get {
                return ResourceManager.GetString("InExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат литерала даты.
        /// </summary>
        internal static string InvalidDateLiteralFormat {
            get {
                return ResourceManager.GetString("InvalidDateLiteralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Именем переменной, функции или процедуры должна быть любая последовательность букв, цифр и знаков подчеркивания, начинающаяся с буквы или знака подчеркивания.
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат числа.
        /// </summary>
        internal static string InvalidNumberLiteralFormat {
            get {
                return ResourceManager.GetString("InvalidNumberLiteralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат строки.
        /// </summary>
        internal static string InvalidStringLiteralFormat {
            get {
                return ResourceManager.GetString("InvalidStringLiteralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается константа примитивного типа (Число, Строка, Дата, Булево, Неопределено, NULL).
        /// </summary>
        internal static string LiteralExpressionExpected {
            get {
                return ResourceManager.GetString("LiteralExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается символ начала метки - ~.
        /// </summary>
        internal static string MarkExpected {
            get {
                return ResourceManager.GetString("MarkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается определение процедуры или функции.
        /// </summary>
        internal static string MethodDefinitionExpected {
            get {
                return ResourceManager.GetString("MethodDefinitionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для функциональной формы создания нового объекта обязательно указание тип объекта в аргументах оператора.
        /// </summary>
        internal static string NewObjectArgumentsExpected {
            get {
                return ResourceManager.GetString("NewObjectArgumentsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается открывающая скобка - (.
        /// </summary>
        internal static string OpenParentExpected {
            get {
                return ResourceManager.GetString("OpenParentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается точка с запятой - ;.
        /// </summary>
        internal static string SemicolonExpected {
            get {
                return ResourceManager.GetString("SemicolonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается инструкция.
        /// </summary>
        internal static string StatementExpected {
            get {
                return ResourceManager.GetString("StatementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;Тогда&quot;.
        /// </summary>
        internal static string ThenExpected {
            get {
                return ResourceManager.GetString("ThenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ключевое слово &quot;По&quot;.
        /// </summary>
        internal static string ToExpected {
            get {
                return ResourceManager.GetString("ToExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключевое слово &quot;Ждать&quot; может использоваться только в методах с модификатором &quot;Асинх&quot;.
        /// </summary>
        internal static string UnexpectedAwaitOperator {
            get {
                return ResourceManager.GetString("UnexpectedAwaitOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено начало области.
        /// </summary>
        internal static string UnexpectedEndRegion {
            get {
                return ResourceManager.GetString("UnexpectedEndRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная инструкция препроцессора.
        /// </summary>
        internal static string UnexpectedPreprocessorDirective {
            get {
                return ResourceManager.GetString("UnexpectedPreprocessorDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неожиданный оператор условия препроцессора.
        /// </summary>
        internal static string UnexpectedPreprocessorExpression {
            get {
                return ResourceManager.GetString("UnexpectedPreprocessorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявления переменных должны быть расположены в начале модуля, процедуры или функции.
        /// </summary>
        internal static string UnexpectedVariableDeclaration {
            get {
                return ResourceManager.GetString("UnexpectedVariableDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный код ошибки ({0}).
        /// </summary>
        internal static string UnknownErrorCode {
            get {
                return ResourceManager.GetString("UnknownErrorCode", resourceCulture);
            }
        }
    }
}
